Pages/Lists/Approval_Requests/Approved.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Approval_Requests
{
    public class ApprovedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Approval_Requests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles="Supervisor")]
    public class CreateModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public CreateModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["Approver"] = new SelectList(_context.Employees, "Id", "FullName");
        ViewData["LeaveRequest"] = new SelectList(_context.LeaveRequests, "Id", "AbsenceReason");
            return Page();
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ApprovalRequests.Add(ApprovalRequest);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Approval_Requests/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles ="Supervisor")]
    public class DeleteModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DeleteModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);

            if (approvalrequest == null)
            {
                return NotFound();
            }
            else
            {
                ApprovalRequest = approvalrequest;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FindAsync(id);
            if (approvalrequest != null)
            {
                ApprovalRequest = approvalrequest;
                _context.ApprovalRequests.Remove(ApprovalRequest);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Approval_Requests/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    public class DetailsModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DetailsModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);
            if (approvalrequest == null)
            {
                return NotFound();
            }
            else
            {
                ApprovalRequest = approvalrequest;
            }
            return Page();
        }
    }
}

Pages/Lists/Approval_Requests/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles = "Supervisor")]
    public class EditModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public EditModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest =  await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);
            if (approvalrequest == null)
            {
                return NotFound();
            }
            ApprovalRequest = approvalrequest;
           ViewData["Approver"] = new SelectList(_context.Employees, "Id", "FullName");
           ViewData["LeaveRequest"] = new SelectList(_context.LeaveRequests, "Id", "AbsenceReason");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ApprovalRequest).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApprovalRequestExists(ApprovalRequest.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ApprovalRequestExists(int id)
        {
            return _context.ApprovalRequests.Any(e => e.Id == id);
        }
    }
}

Pages/Lists/Approval_Requests/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles = "Supervisor,Admin,HR,PM")]
    public class IndexModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;
        private readonly SignInManager<Employee> _signInManager;

        public IndexModel(SmartItApp.Models.SmartItAppContext context, SignInManager<Employee> signInManager)
        {
            _context = context;
            _signInManager= signInManager;
        }

        public IList<ApprovalRequest> ApprovalRequest { get; set; } = default!;
        [BindProperty]
        public int SearchString { get; set; }
        public string CurrentSortOrder { get; set; }

        public async Task OnGetAsync(string sortOrder)
        {
            CurrentSortOrder = sortOrder ?? "Id_asc";
            IQueryable<ApprovalRequest> approvalRequestsIQ = from s in _context.ApprovalRequests
                                                             select s;

            approvalRequestsIQ = sortOrder switch
            {
                "Approver_asc" => approvalRequestsIQ.OrderBy(s => s.Approver),
                "Approver_desc" => approvalRequestsIQ.OrderByDescending(s => s.Approver),
                "Id_desc" => approvalRequestsIQ.OrderByDescending(s => s.Id),
                "LeaveRequest_asc" => approvalRequestsIQ.OrderBy(s => s.LeaveRequest),
                "LeaveRequest_desc" => approvalRequestsIQ.OrderByDescending(s => s.LeaveRequest),
                "EmployeeId_asc" => approvalRequestsIQ.OrderBy(s => s.EmployeeId),
                "EmployeeId_desc" => approvalRequestsIQ.OrderByDescending(s => s.EmployeeId),
                "Status_asc" => approvalRequestsIQ.OrderBy(s => s.Status),
                "Status_desc" => approvalRequestsIQ.OrderByDescending(s => s.Status),
                _ => approvalRequestsIQ.OrderBy(s => s.Id),
            };

            ApprovalRequest = await approvalRequestsIQ.AsNoTracking().ToListAsync();
        }

        public async Task OnPostFindAsync()
        {
            ApprovalRequest = await _context.ApprovalRequests.Where(x => x.Id == SearchString).ToListAsync();
        }

        public string GetSortOrder(string columnName, string currentSortOrder)
        {
            if (string.IsNullOrEmpty(currentSortOrder) || !currentSortOrder.StartsWith(columnName))
            {
                return columnName + "_asc";
            }
            else if (currentSortOrder.EndsWith("_asc"))
            {
                return columnName + "_desc";
            }
            else
            {
                return columnName + "_asc";
            }
        }
        public async Task<IActionResult> OnPostApproveRequestAsync(int? id)
        {
            var approvalRequest= await _context.ApprovalRequests.FindAsync(id);
            if (approvalRequest == null)
            {
                return NotFound();
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(approvalRequest.LeaveRequest);
            var employee = await _context.Employees.FindAsync(leaveRequest.Employee);
            approvalRequest.Status = SmartItApp.Enums.RequestStatus.Approved.ToString();
            leaveRequest.Status = SmartItApp.Enums.RequestStatus.Approved.ToString();
            TimeSpan difference = leaveRequest.EndDate.ToDateTime(TimeOnly.Parse("10:00 PM")) - leaveRequest.StartDate.ToDateTime(TimeOnly.Parse("10:00 PM"));
            employee.DaysOff-=difference.Days;
            leaveRequest.Comment = "Approved";
            approvalRequest.Approver = (await _signInManager.UserManager.GetUserAsync(User)).Id;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Approved");
        }
        public async Task<IActionResult> OnPostRejectRequestAsync(int? id,string rejectReason)
        {
            var approvalRequest = await _context.ApprovalRequests.FindAsync(id);
            if (approvalRequest == null)
            {
                return NotFound();
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(approvalRequest.LeaveRequest);
            approvalRequest.Status = SmartItApp.Enums.RequestStatus.Rejected.ToString();
            leaveRequest.Status = SmartItApp.Enums.RequestStatus.Rejected.ToString();
            leaveRequest.Comment = rejectReason;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Rejected");
        }
    }
}

Pages/Lists/Approval_Requests/Rejected.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Approval_Requests
{
    public class RejectedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Leave_Requests/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Leave_Requests
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;
        private readonly SignInManager<Employee> _signInManager;

        public IndexModel(SmartItApp.Models.SmartItAppContext context, SignInManager<Employee> signInManager)
        {
            _context = context;
            _signInManager = signInManager;
        }

        public Employee employee { get; set; } = default!;
        [BindProperty]
        public int SearchString { get; set; }
        public string CurrentSortOrder { get; set; }
        public IList<LeaveRequest> LeaveRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(string sortOrder)
        {
            if (!_signInManager.IsSignedIn(User))
            {
                return Redirect("/Identity/Account/Login");
            }

            CurrentSortOrder = sortOrder ?? "Id_asc";
            IQueryable<LeaveRequest> LeaveRequestsIQ = from s in _context.LeaveRequests
                                                       select s;
            LeaveRequestsIQ = sortOrder switch
            {
                "Id_desc" => LeaveRequestsIQ.OrderByDescending(e => e.Id),
                "Employee_asc" => LeaveRequestsIQ.OrderBy(e => e.Employee),
                "Employee_desc" => LeaveRequestsIQ.OrderByDescending(e => e.Employee),
                "AbsenceReason_asc" => LeaveRequestsIQ.OrderBy(e => e.AbsenceReason),
                "AbsenceReason_desc" => LeaveRequestsIQ.OrderByDescending(e => e.AbsenceReason),
                "StartDate_asc" => LeaveRequestsIQ.OrderBy(e => e.StartDate),
                "StartDate_desc" => LeaveRequestsIQ.OrderByDescending(e => e.StartDate),
                "EndDate_asc" => LeaveRequestsIQ.OrderBy(e => e.EndDate),
                "EndDate_desc" => LeaveRequestsIQ.OrderByDescending(e => e.EndDate),
                "Comment_asc" => LeaveRequestsIQ.OrderBy(e => e.Comment),
                "Comment_desc" => LeaveRequestsIQ.OrderByDescending(e => e.Comment),
                "Status_asc" => LeaveRequestsIQ.OrderBy(e => e.Status),
                "Status_desc" => LeaveRequestsIQ.OrderByDescending(e => e.Status),
                _ => LeaveRequestsIQ.OrderBy(e => e.Id) 
            };

            var user = await _signInManager.UserManager.GetUserAsync(User);
            if (User.IsInRole("Admin") || User.IsInRole("Supervisor"))
            {
                LeaveRequest = await LeaveRequestsIQ.AsNoTracking().ToListAsync();
            }
            else if (User.IsInRole("HR") || User.IsInRole("PM"))
            {
                var currentUser = await _signInManager.UserManager.GetUserAsync(User);
                var subdivision = currentUser.Subdivision;
                LeaveRequest = await LeaveRequestsIQ
                    .Where(lr => _context.Employees.Any(e => e.Id == lr.Employee && e.Subdivision == subdivision))
                    .AsNoTracking()
                    .ToListAsync();
            }
            else if (User.IsInRole("Employee"))
            {
                LeaveRequest = await LeaveRequestsIQ.Where(x => x.Employee == user.Id).AsNoTracking().ToListAsync();
                employee = user;
            }

            return Page();
        }

        public async Task OnPostFindAsync()
        {
            var user = await _signInManager.UserManager.GetUserAsync(User);
            if (User.IsInRole("Employee"))
            {
                LeaveRequest = await _context.LeaveRequests.Where(x => x.Id == SearchString && x.Employee==user.Id).ToListAsync();
            }
            else
            {
                LeaveRequest = await _context.LeaveRequests.Where(x => x.Id == SearchString).ToListAsync();
            }
        }

        public string GetSortOrder(string columnName, string currentSortOrder)
        {
            if (string.IsNullOrEmpty(currentSortOrder) || !currentSortOrder.StartsWith(columnName))
            {
                return columnName + "_asc";
            }
            else if (currentSortOrder.EndsWith("_asc"))
            {
                return columnName + "_desc";
            }
            else
            {
                return columnName + "_asc";
            }
        }
        public async Task<IActionResult> OnPostSubmitAsync(int? id)
        {
            if(id== null)
            {
                return NotFound();
            }
            LeaveRequest leaveRequest = await _context.LeaveRequests.FindAsync(id);
            ApprovalRequest approvalRequest = new ApprovalRequest();
            approvalRequest.LeaveRequest = leaveRequest.Id;
            approvalRequest.Approver = 4;
            leaveRequest.Status=Enums.RequestStatus.Submitted.ToString();
            approvalRequest.Status=Enums.RequestStatus.Submitted.ToString();
            approvalRequest.EmployeeId = leaveRequest.Employee;
            await _context.ApprovalRequests.AddAsync(approvalRequest);
            await _context.SaveChangesAsync();
            return RedirectToPage("./Submitted");

        }
    }
}

Pages/Lists/Leave_Requests/Create.cshtml
@page
@model SmartItApp.Pages.Lists.Leave_Requests.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>LeaveRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeaveRequest.AbsenceReason" class="control-label"></label>
                <input asp-for="LeaveRequest.AbsenceReason" class="form-control" />
                <span asp-validation-for="LeaveRequest.AbsenceReason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveRequest.StartDate" class="control-label"></label>
                <input asp-for="LeaveRequest.StartDate" type="date" class="form-control" />
                <span asp-validation-for="LeaveRequest.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveRequest.EndDate" class="control-label"></label>
                <input asp-for="LeaveRequest.EndDate" type="date" class="form-control" />
                <span asp-validation-for="LeaveRequest.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="LeaveRequest.Status" type="hidden" value="@SmartItApp.Enums.RequestStatus.New.ToString()" class="form-control" />
                <span asp-validation-for="LeaveRequest.Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Lists/Leave_Requests/Delete.cshtml
@page
@model SmartItApp.Pages.Lists.Leave_Requests.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LeaveRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Employee Id
        </dt>
        <dd class="col-sm-10">
            @Model.LeaveRequest.Employee
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.AbsenceReason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.AbsenceReason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.Comment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.Comment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.Status)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="LeaveRequest.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Lists/Leave_Requests/Details.cshtml
@page
@model SmartItApp.Pages.Lists.Leave_Requests.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>LeaveRequest</h4>
    <hr />
    <dl class="row">
        
            @if(User.IsInRole("Admin")|| User.IsInRole("HR") || User.IsInRole("PM")){
            <dt class="col-sm-2">
            <a asp-page="/Lists/Employees/Details" asp-route-id="@Model.LeaveRequest.Employee">
            Employee Id
            </a>
            </dt>
            }
            else 
            {
            <dt class="col-sm-2">
                Employee Id
                 </dt>
                
            }
       
        <dd class="col-sm-10">
            @Model.LeaveRequest.Employee
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.AbsenceReason)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.AbsenceReason)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.Comment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.Comment)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveRequest.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveRequest.Status)
        </dd>

    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.LeaveRequest.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Lists/Leave_Requests/Index.cshtml
@page
@model SmartItApp.Pages.Lists.Leave_Requests.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Leave Requests</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">
    <div class="container">
        <div class="row height d-flex justify-content-center align-items-center">
            <div class="col-md-6">
                <div class="form d-flex" style="margin-bottom:10px">
                    <form method="post" asp-page-handler="Find" class="d-flex w-100">
                        <input asp-for="SearchString" type="number" class="form-control form-input" placeholder="Search by Request ID">
                        <button class="btn btn-outline-dark mt-auto" style="margin-inline-start:10px" type="submit">Find</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Id", Model.CurrentSortOrder)">
                    Request Id
                </a>
            </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Employee", Model.CurrentSortOrder)">
                    Employee Id
                </a>
            </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("AbsenceReason", Model.CurrentSortOrder)">
                    @Html.DisplayNameFor(model => model.LeaveRequest[0].AbsenceReason)
                </a>
            </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("StartDate", Model.CurrentSortOrder)">
                    @Html.DisplayNameFor(model => model.LeaveRequest[0].StartDate)
                </a>
            </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("EndDate", Model.CurrentSortOrder)">
                    @Html.DisplayNameFor(model => model.LeaveRequest[0].EndDate)
                </a>
            </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Comment", Model.CurrentSortOrder)">
                    @Html.DisplayNameFor(model => model.LeaveRequest[0].Comment)
                </a>
            </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Status", Model.CurrentSortOrder)">
                    @Html.DisplayNameFor(model => model.LeaveRequest[0].Status)
                </a>
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequest)
        {
            <tr>
                <td>
                    @item.Id
                </td>
                <td>
                    @item.Employee
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AbsenceReason)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> 
                        @if (User.IsInRole("Admin") || User.IsInRole("Supervisor") || item.Status==SmartItApp.Enums.RequestStatus.New.ToString())
                        {
                            <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                    }
                    </td>
                    <td>
                        @if (User.IsInRole("Employee") && item.Status != SmartItApp.Enums.RequestStatus.Submitted.ToString())
                        {
                            <form method="post" asp-page-handler="Submit">
                                <input type="hidden" name="id" value="@item.Id" />
                                <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                                    Submit
                                </button>
                            </form>
                        }
                    </td>
            </tr>
        }
    </tbody>
</table>

Pages/Lists/Leave_Requests/Submitted.cshtml
@page
@model SmartItApp.Pages.Lists.Leave_Requests.SubmittedModel
@{
}
<h1>
    Your leave request has been submitted
</h1>