Pages/Lists/Approval_Requests/Approved.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Approval_Requests
{
    public class ApprovedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Approval_Requests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles="Supervisor")]
    public class CreateModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public CreateModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["Approver"] = new SelectList(_context.Employees, "Id", "FullName");
        ViewData["LeaveRequest"] = new SelectList(_context.LeaveRequests, "Id", "AbsenceReason");
            return Page();
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ApprovalRequests.Add(ApprovalRequest);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Approval_Requests/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles ="Supervisor")]
    public class DeleteModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DeleteModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);

            if (approvalrequest == null)
            {
                return NotFound();
            }
            else
            {
                ApprovalRequest = approvalrequest;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FindAsync(id);
            if (approvalrequest != null)
            {
                ApprovalRequest = approvalrequest;
                _context.ApprovalRequests.Remove(ApprovalRequest);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Approval_Requests/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    public class DetailsModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DetailsModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);
            if (approvalrequest == null)
            {
                return NotFound();
            }
            else
            {
                ApprovalRequest = approvalrequest;
            }
            return Page();
        }
    }
}

Pages/Lists/Approval_Requests/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles = "Supervisor")]
    public class EditModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public EditModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest =  await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);
            if (approvalrequest == null)
            {
                return NotFound();
            }
            ApprovalRequest = approvalrequest;
           ViewData["Approver"] = new SelectList(_context.Employees, "Id", "FullName");
           ViewData["LeaveRequest"] = new SelectList(_context.LeaveRequests, "Id", "AbsenceReason");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ApprovalRequest).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApprovalRequestExists(ApprovalRequest.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ApprovalRequestExists(int id)
        {
            return _context.ApprovalRequests.Any(e => e.Id == id);
        }
    }
}

Pages/Lists/Approval_Requests/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles = "Supervisor,Admin,HR,PM")]
    public class IndexModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;
        private readonly SignInManager<Employee> _signInManager;

        public IndexModel(SmartItApp.Models.SmartItAppContext context, SignInManager<Employee> signInManager)
        {
            _context = context;
            _signInManager= signInManager;
        }

        public IList<ApprovalRequest> ApprovalRequest { get; set; } = default!;
        [BindProperty]
        public int SearchString { get; set; }
        public string CurrentSortOrder { get; set; }

        public async Task OnGetAsync(string sortOrder)
        {
            CurrentSortOrder = sortOrder ?? "Id_asc";
            IQueryable<ApprovalRequest> approvalRequestsIQ = from s in _context.ApprovalRequests
                                                             select s;

            approvalRequestsIQ = sortOrder switch
            {
                "Approver_asc" => approvalRequestsIQ.OrderBy(s => s.Approver),
                "Approver_desc" => approvalRequestsIQ.OrderByDescending(s => s.Approver),
                "Id_desc" => approvalRequestsIQ.OrderByDescending(s => s.Id),
                "LeaveRequest_asc" => approvalRequestsIQ.OrderBy(s => s.LeaveRequest),
                "LeaveRequest_desc" => approvalRequestsIQ.OrderByDescending(s => s.LeaveRequest),
                "EmployeeId_asc" => approvalRequestsIQ.OrderBy(s => s.EmployeeId),
                "EmployeeId_desc" => approvalRequestsIQ.OrderByDescending(s => s.EmployeeId),
                "Status_asc" => approvalRequestsIQ.OrderBy(s => s.Status),
                "Status_desc" => approvalRequestsIQ.OrderByDescending(s => s.Status),
                _ => approvalRequestsIQ.OrderBy(s => s.Id),
            };

            ApprovalRequest = await approvalRequestsIQ.AsNoTracking().ToListAsync();
        }

        public async Task OnPostFindAsync()
        {
            ApprovalRequest = await _context.ApprovalRequests.Where(x => x.Id == SearchString).ToListAsync();
        }

        public string GetSortOrder(string columnName, string currentSortOrder)
        {
            if (string.IsNullOrEmpty(currentSortOrder) || !currentSortOrder.StartsWith(columnName))
            {
                return columnName + "_asc";
            }
            else if (currentSortOrder.EndsWith("_asc"))
            {
                return columnName + "_desc";
            }
            else
            {
                return columnName + "_asc";
            }
        }
        public async Task<IActionResult> OnPostApproveRequestAsync(int? id)
        {
            var approvalRequest= await _context.ApprovalRequests.FindAsync(id);
            if (approvalRequest == null)
            {
                return NotFound();
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(approvalRequest.LeaveRequest);
            var employee = await _context.Employees.FindAsync(leaveRequest.Employee);
            approvalRequest.Status = SmartItApp.Enums.RequestStatus.Approved.ToString();
            leaveRequest.Status = SmartItApp.Enums.RequestStatus.Approved.ToString();
            TimeSpan difference = leaveRequest.EndDate.ToDateTime(TimeOnly.Parse("10:00 PM")) - leaveRequest.StartDate.ToDateTime(TimeOnly.Parse("10:00 PM"));
            employee.DaysOff-=difference.Days;
            leaveRequest.Comment = "Approved";
            approvalRequest.Approver = (await _signInManager.UserManager.GetUserAsync(User)).Id;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Approved");
        }
        public async Task<IActionResult> OnPostRejectRequestAsync(int? id,string rejectReason)
        {
            var approvalRequest = await _context.ApprovalRequests.FindAsync(id);
            if (approvalRequest == null)
            {
                return NotFound();
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(approvalRequest.LeaveRequest);
            approvalRequest.Status = SmartItApp.Enums.RequestStatus.Rejected.ToString();
            leaveRequest.Status = SmartItApp.Enums.RequestStatus.Rejected.ToString();
            leaveRequest.Comment = rejectReason;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Rejected");
        }
    }
}

Pages/Lists/Approval_Requests/Rejected.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Approval_Requests
{
    public class RejectedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Employees
{
    [Authorize(Policy ="Supervisor")]
    public class DeleteModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DeleteModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);

            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee != null)
            {
                Employee = employee;
                _context.Employees.Remove(Employee);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Employees
{
    [Authorize(Roles = "Supervisor,Admin,HR,PM")]
    public class DetailsModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DetailsModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

Pages/Lists/Leave_Requests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Leave_Requests
{
    [Authorize]
    public class CreateModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;
        private readonly SignInManager <Employee> _signInManager;

        public CreateModel(SmartItApp.Models.SmartItAppContext context, SignInManager<Employee> signInManager)
        {
            _context = context;
            _signInManager = signInManager;
        }

        public IActionResult OnGet()
        {
        
        ViewData["Employee"] = new SelectList(_context.Employees, "Id", "FullName");
            return Page();
        }

        [BindProperty]
        public LeaveRequest LeaveRequest { get; set; } = default!;

        public async Task<IActionResult> OnPostAsync()
        {
            Employee employee = await _signInManager.UserManager.GetUserAsync(User);
            LeaveRequest.Employee = employee.Id;
            TimeSpan difference = LeaveRequest.EndDate.ToDateTime(TimeOnly.Parse("10:00 PM")) - LeaveRequest.StartDate.ToDateTime(TimeOnly.Parse("10:00 PM"));
            if(DateTime.Compare(LeaveRequest.StartDate.ToDateTime(TimeOnly.Parse("10:00 PM")), DateTime.Now)<0)
            {
                ModelState.AddModelError("LeaveRequest.StartDate", "Start Date is earlier than now");
            }
            if (difference.Days < 0)
            {
                ModelState.AddModelError("LeaveRequest.EndDate", "You chose wrong Start date End date interval");
            }
            int DaysDifference = difference.Days;
            if (DaysDifference > employee.DaysOff)
            {
               ModelState.AddModelError("LeaveRequest.EndDate", "You do not have enough days off or ");
            }
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _context.LeaveRequests.Add(LeaveRequest);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Leave_Requests/Submitted.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Leave_Requests
{
    public class SubmittedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Approval_Requests/Approved.cshtml
@page
@model SmartItApp.Pages.Lists.Approval_Requests.ApprovedModel
@{
}
<h1>
    Request has been approved
</h1>

Pages/Lists/Approval_Requests/Create.cshtml
@page
@model SmartItApp.Pages.Lists.Aproval_Requests.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ApprovalRequest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ApprovalRequest.Approver" class="control-label"></label>
                <select asp-for="ApprovalRequest.Approver" class ="form-control" asp-items="ViewBag.Approver"></select>
            </div>
            <div class="form-group">
                <label asp-for="ApprovalRequest.LeaveRequest" class="control-label"></label>
                <select asp-for="ApprovalRequest.LeaveRequest" class ="form-control" asp-items="ViewBag.LeaveRequest"></select>
            </div>
            <div class="form-group">
                <label asp-for="ApprovalRequest.Status" class="control-label"></label>
                <input asp-for="ApprovalRequest.Status" class="form-control" />
                <span asp-validation-for="ApprovalRequest.Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Lists/Approval_Requests/Delete.cshtml
@page
@model SmartItApp.Pages.Lists.Aproval_Requests.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApprovalRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalRequest.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.Id)
        </dd>
        <dt class="col-sm-2">
            <a asp-page="/Lists/Employees/Details" asp-route-id="@Model.ApprovalRequest.EmployeeId">
                @Html.DisplayNameFor(model => model.ApprovalRequest.EmployeeId)
            </a>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.EmployeeId)
        </dd>
        <dt class="col-sm-2">
            <a asp-page="/Lists/Employees/Details" asp-route-id="@Model.ApprovalRequest.Approver">
                @Html.DisplayNameFor(model => model.ApprovalRequest.Approver)
            </a>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.Approver)
        </dd>
        <dt class="col-sm-2">
            <a asp-page="/Lists/Leave_Requests/Details" asp-route-id="@Model.ApprovalRequest.LeaveRequest">
                @Html.DisplayNameFor(model => model.ApprovalRequest.LeaveRequest)
            </a>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.LeaveRequest)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalRequest.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.Status)
        </dd>

    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="ApprovalRequest.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Lists/Approval_Requests/Details.cshtml
@page
@model SmartItApp.Pages.Lists.Aproval_Requests.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ApprovalRequest</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalRequest.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.Id)
        </dd>
        <dt class="col-sm-2">
            <a asp-page="/Lists/Employees/Details" asp-route-id="@Model.ApprovalRequest.EmployeeId">
                @Html.DisplayNameFor(model => model.ApprovalRequest.EmployeeId)
            </a>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.EmployeeId)
        </dd>
        <dt class="col-sm-2">
            <a asp-page="/Lists/Employees/Details" asp-route-id="@Model.ApprovalRequest.Approver">
            @Html.DisplayNameFor(model => model.ApprovalRequest.Approver)
            </a>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.Approver)
        </dd>
        <dt class="col-sm-2">
            <a asp-page="/Lists/Leave_Requests/Details" asp-route-id="@Model.ApprovalRequest.LeaveRequest">
            @Html.DisplayNameFor(model => model.ApprovalRequest.LeaveRequest)
            </a>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.LeaveRequest)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalRequest.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalRequest.Status)
        </dd>

    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.ApprovalRequest.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Lists/Approval_Requests/Index.cshtml
@page
@model SmartItApp.Pages.Lists.Aproval_Requests.IndexModel

@{
    ViewData["Title"] = "Approval Requests";
}

<h1>Approval Requests</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>

<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">
    <div class="container">
        <div class="row height d-flex justify-content-center align-items-center">
            <div class="col-md-6">
                <div class="form d-flex" style="margin-bottom:10px">
                    <form method="post" asp-page-handler="Find" class="d-flex w-100">
                        <input asp-for="SearchString" type="number" class="form-control form-input" placeholder="Search by Request ID">
                        <button class="btn btn-outline-dark mt-auto" style="margin-inline-start:10px" type="submit">Find</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Id", Model.CurrentSortOrder)">
                        Request Id
                    </a>
                </th>
                <th>
                    <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("LeaveRequest", Model.CurrentSortOrder)">
                        LeaveRequest ID
                    </a>
                </th>
                <th>
                    <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("EmployeeId", Model.CurrentSortOrder)">
                        Employee ID
                    </a>
                </th>
                <th>
                    <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Approver", Model.CurrentSortOrder)">
                        Approver ID
                    </a>
                </th>
                <th>
                    <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Status", Model.CurrentSortOrder)">
                        @Html.DisplayNameFor(model => model.ApprovalRequest[0].Status)
                    </a>
                </th>
                <th>

                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ApprovalRequest)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LeaveRequest)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EmployeeId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Approver)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @if (User.IsInRole("Supervisor"))
                        {
                            <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
                            <a asp-page = "./Delete" asp-route-id ="@item.Id">Delete</a>
                        }   
                        <a asp-page="./Details" asp-route-id="@item.Id">Details</a>
                    </td>
                    @if (item.Status != SmartItApp.Enums.RequestStatus.Approved.ToString())
                    {
                        <td>
                        <form method="post" asp-page-handler="ApproveRequest">
                            <input type="hidden" name="id" value="@item.Id" />
                                <button class="btn btn-success" type="submit">
                                Approve Request
                            </button>
                        </form>
                        </td>
                    }
                    @if (item.Status != SmartItApp.Enums.RequestStatus.Rejected.ToString())
                    {
                        <td>
                            <button type="button" class="btn btn-outline-danger" onclick="showRejectModal('@item.Id')">Reject Request</button>
                        </td>
                    }
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="modal fade" id="rejectModal" tabindex="-1" aria-labelledby="rejectModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="rejectModalLabel">Reject Request</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" asp-page-handler="RejectRequest" id="rejectForm">
                    <input type="hidden" id="rejectRequestId" name="id" />
                    <div class="mb-3">
                        <label for="rejectReason" class="form-label">Reason for Rejection</label>
                        <textarea class="form-control" id="rejectReason" name="rejectReason" rows="3" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function showRejectModal(requestId) {
            var rejectModal = new bootstrap.Modal(document.getElementById('rejectModal'));
            document.getElementById('rejectRequestId').value = requestId;
            rejectModal.show();
        }
    </script>
}