Pages/Lists/Approval_Requests/Approved.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Approval_Requests
{
    public class ApprovedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Approval_Requests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles="Supervisor")]
    public class CreateModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public CreateModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["Approver"] = new SelectList(_context.Employees, "Id", "FullName");
        ViewData["LeaveRequest"] = new SelectList(_context.LeaveRequests, "Id", "AbsenceReason");
            return Page();
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.ApprovalRequests.Add(ApprovalRequest);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Approval_Requests/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles ="Supervisor")]
    public class DeleteModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DeleteModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);

            if (approvalrequest == null)
            {
                return NotFound();
            }
            else
            {
                ApprovalRequest = approvalrequest;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FindAsync(id);
            if (approvalrequest != null)
            {
                ApprovalRequest = approvalrequest;
                _context.ApprovalRequests.Remove(ApprovalRequest);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Approval_Requests/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    public class DetailsModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DetailsModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest = await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);
            if (approvalrequest == null)
            {
                return NotFound();
            }
            else
            {
                ApprovalRequest = approvalrequest;
            }
            return Page();
        }
    }
}

Pages/Lists/Approval_Requests/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles = "Supervisor")]
    public class EditModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public EditModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ApprovalRequest ApprovalRequest { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var approvalrequest =  await _context.ApprovalRequests.FirstOrDefaultAsync(m => m.Id == id);
            if (approvalrequest == null)
            {
                return NotFound();
            }
            ApprovalRequest = approvalrequest;
           ViewData["Approver"] = new SelectList(_context.Employees, "Id", "FullName");
           ViewData["LeaveRequest"] = new SelectList(_context.LeaveRequests, "Id", "AbsenceReason");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ApprovalRequest).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ApprovalRequestExists(ApprovalRequest.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ApprovalRequestExists(int id)
        {
            return _context.ApprovalRequests.Any(e => e.Id == id);
        }
    }
}

Pages/Lists/Approval_Requests/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Aproval_Requests
{
    [Authorize(Roles = "Supervisor,Admin,HR,PM")]
    public class IndexModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;
        private readonly SignInManager<Employee> _signInManager;

        public IndexModel(SmartItApp.Models.SmartItAppContext context, SignInManager<Employee> signInManager)
        {
            _context = context;
            _signInManager= signInManager;
        }

        public IList<ApprovalRequest> ApprovalRequest { get; set; } = default!;
        [BindProperty]
        public int SearchString { get; set; }
        public string CurrentSortOrder { get; set; }

        public async Task OnGetAsync(string sortOrder)
        {
            CurrentSortOrder = sortOrder ?? "Id_asc";
            IQueryable<ApprovalRequest> approvalRequestsIQ = from s in _context.ApprovalRequests
                                                             select s;

            approvalRequestsIQ = sortOrder switch
            {
                "Approver_asc" => approvalRequestsIQ.OrderBy(s => s.Approver),
                "Approver_desc" => approvalRequestsIQ.OrderByDescending(s => s.Approver),
                "Id_desc" => approvalRequestsIQ.OrderByDescending(s => s.Id),
                "LeaveRequest_asc" => approvalRequestsIQ.OrderBy(s => s.LeaveRequest),
                "LeaveRequest_desc" => approvalRequestsIQ.OrderByDescending(s => s.LeaveRequest),
                "EmployeeId_asc" => approvalRequestsIQ.OrderBy(s => s.EmployeeId),
                "EmployeeId_desc" => approvalRequestsIQ.OrderByDescending(s => s.EmployeeId),
                "Status_asc" => approvalRequestsIQ.OrderBy(s => s.Status),
                "Status_desc" => approvalRequestsIQ.OrderByDescending(s => s.Status),
                _ => approvalRequestsIQ.OrderBy(s => s.Id),
            };

            ApprovalRequest = await approvalRequestsIQ.AsNoTracking().ToListAsync();
        }

        public async Task OnPostFindAsync()
        {
            ApprovalRequest = await _context.ApprovalRequests.Where(x => x.Id == SearchString).ToListAsync();
        }

        public string GetSortOrder(string columnName, string currentSortOrder)
        {
            if (string.IsNullOrEmpty(currentSortOrder) || !currentSortOrder.StartsWith(columnName))
            {
                return columnName + "_asc";
            }
            else if (currentSortOrder.EndsWith("_asc"))
            {
                return columnName + "_desc";
            }
            else
            {
                return columnName + "_asc";
            }
        }
        public async Task<IActionResult> OnPostApproveRequestAsync(int? id)
        {
            var approvalRequest= await _context.ApprovalRequests.FindAsync(id);
            if (approvalRequest == null)
            {
                return NotFound();
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(approvalRequest.LeaveRequest);
            var employee = await _context.Employees.FindAsync(leaveRequest.Employee);
            approvalRequest.Status = SmartItApp.Enums.RequestStatus.Approved.ToString();
            leaveRequest.Status = SmartItApp.Enums.RequestStatus.Approved.ToString();
            TimeSpan difference = leaveRequest.EndDate.ToDateTime(TimeOnly.Parse("10:00 PM")) - leaveRequest.StartDate.ToDateTime(TimeOnly.Parse("10:00 PM"));
            employee.DaysOff-=difference.Days;
            leaveRequest.Comment = "Approved";
            approvalRequest.Approver = (await _signInManager.UserManager.GetUserAsync(User)).Id;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Approved");
        }
        public async Task<IActionResult> OnPostRejectRequestAsync(int? id,string rejectReason)
        {
            var approvalRequest = await _context.ApprovalRequests.FindAsync(id);
            if (approvalRequest == null)
            {
                return NotFound();
            }
            var leaveRequest = await _context.LeaveRequests.FindAsync(approvalRequest.LeaveRequest);
            approvalRequest.Status = SmartItApp.Enums.RequestStatus.Rejected.ToString();
            leaveRequest.Status = SmartItApp.Enums.RequestStatus.Rejected.ToString();
            leaveRequest.Comment = rejectReason;
            await _context.SaveChangesAsync();
            return RedirectToPage("./Rejected");
        }
    }
}

Pages/Lists/Approval_Requests/Rejected.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Approval_Requests
{
    public class RejectedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Employees
{
    [Authorize(Roles = "Supervisor,Admin,HR,PM")]
    public class DetailsModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;

        public DetailsModel(SmartItApp.Models.SmartItAppContext context)
        {
            _context = context;
        }

        public Employee Employee { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            else
            {
                Employee = employee;
            }
            return Page();
        }
    }
}

Pages/Lists/Employees/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SmartItApp.Models;

namespace SmartItApp.Pages.Lists.Employees
{
    [Authorize(Roles = "Supervisor,Admin,HR,PM")]
    public class IndexModel : PageModel
    {
        private readonly SmartItApp.Models.SmartItAppContext _context;
        private readonly UserManager<Employee> _userManager;
        public IndexModel(SmartItApp.Models.SmartItAppContext context, UserManager<Employee> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public IList<Employee> Employee { get;set; } = default!;
        [BindProperty]
        public string SearchString { get; set;  }
        [BindProperty]
        public int SearchStringId { get; set; }
        public string CurrentSortOrder { get; set; }
        public async Task OnGetAsync(string sortOrder)
        {
            CurrentSortOrder = sortOrder;
            IQueryable<Employee> employeesIQ = from e in _context.Employees
                                               select e;

            employeesIQ = sortOrder switch
            {
                "Id"=> employeesIQ.OrderBy(e => e.Id),
                "Id_desc" => employeesIQ.OrderByDescending(e => e.Id),
                "FullName" => employeesIQ.OrderBy(e => e.FullName),
                "FullName_desc" => employeesIQ.OrderByDescending(e => e.FullName),
                "Subdivision" => employeesIQ.OrderBy(e => e.Subdivision),
                "Subdivision_desc" => employeesIQ.OrderByDescending(e => e.Subdivision),
                "Position" => employeesIQ.OrderBy(e => e.Position),
                "Position_desc" => employeesIQ.OrderByDescending(e => e.Position),
                "Status" => employeesIQ.OrderBy(e => e.Status),
                "Status_desc" => employeesIQ.OrderByDescending(e => e.Status),
                "DaysOff" => employeesIQ.OrderBy(e => e.DaysOff),
                "DaysOff_desc" => employeesIQ.OrderByDescending(e => e.DaysOff),
                _ => employeesIQ.OrderBy(e => e.FullName),
            };
            Employee = await employeesIQ.AsNoTracking().ToListAsync();
        }

        public async Task OnPostFindAsync()
        {
            Employee = await _context.Employees.Where(x => x.FullName.Contains(SearchString) && x.Position!="Supervisor").ToListAsync();
        }
        public async Task OnPostFindIdAsync()
        {
            Employee = await _context.Employees.Where(x => x.Id == (SearchStringId)).ToListAsync();
        }
        public string GetSortOrder(string columnName, string currentSortOrder)
        {
            if (string.IsNullOrEmpty(currentSortOrder) || !currentSortOrder.StartsWith(columnName))
            {
                return columnName;
            }
            else if (currentSortOrder.EndsWith("_desc"))
            {
                return columnName;
            }
            else
            {
                return columnName + "_desc";
            }
        }
        public async Task<IActionResult> OnPostChangeStatusAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            if(employee.Status == SmartItApp.Enums.Statuses.Active.ToString())
            {
                employee.Status = SmartItApp.Enums.Statuses.Inactive.ToString();
            }
            else
            {
                employee.Status = SmartItApp.Enums.Statuses.Active.ToString();
            }
            await _context.SaveChangesAsync();
            return RedirectToPage("./Index");
        }
    }
}

Pages/Lists/Leave_Requests/Submitted.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SmartItApp.Pages.Lists.Leave_Requests
{
    public class SubmittedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Lists/Employees/Delete.cshtml
@page
@model SmartItApp.Pages.Lists.Employees.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.FullName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Subdivision)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Subdivision)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Position)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Position)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.DaysOff)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.DaysOff)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Photo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Photo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.PeoplePartnerNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.PeoplePartnerNavigation.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.NormalizedUserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.NormalizedUserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.NormalizedEmail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.NormalizedEmail)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.EmailConfirmed)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.EmailConfirmed)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.PasswordHash)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.PasswordHash)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.SecurityStamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.SecurityStamp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.ConcurrencyStamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.ConcurrencyStamp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.PhoneNumberConfirmed)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.PhoneNumberConfirmed)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.TwoFactorEnabled)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.TwoFactorEnabled)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.LockoutEnd)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.LockoutEnd)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.LockoutEnabled)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.LockoutEnabled)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.AccessFailedCount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.AccessFailedCount)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Employee.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Lists/Employees/Index.cshtml
@page
@model SmartItApp.Pages.Lists.Employees.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Employees</h1>

<p>
    @if (User.IsInRole("Admin") || User.IsInRole("HR"))
    {
        <button type="button" class="btn btn-success">
            <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Add Employee</a>
        </button>
    }
</p>
<div style="display: flex; flex-wrap: wrap; justify-content: space-between;">
<div class="container">
    <div class="row height d-flex justify-content-center align-items-center">
        <div class="col-md-6">
            <div class="form d-flex" style="margin-bottom:10px">
                    <form method="post" asp-page-handler="Find" class="d-flex w-100">
                    <input asp-for="SearchString" class="form-control form-input" placeholder="Search by name">
                    <button class="btn btn-outline-dark mt-auto" style="margin-inline-start:10px" type="submit">Find</button>
                </form>
            </div>
                <div class="form d-flex" style="margin-bottom:10px">
                    <form method="post" asp-page-handler="FindId" class="d-flex w-100">
                        <input asp-for="SearchStringId" class="form-control form-input" placeholder="Search by ID">
                        <button class="btn btn-outline-dark mt-auto" style="margin-inline-start:10px" type="submit">Find</button>
                    </form>
                </div>
        </div>
    </div>
</div>


<table class="table">

    <thead>
        <tr>
                <th>
                    <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Id",Model.CurrentSortOrder)">
                        @Html.DisplayNameFor(model => model.Employee[0].Id)
                    </a>
                </th>
            <th>
                <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("FullName",Model.CurrentSortOrder)">
                @Html.DisplayNameFor(model => model.Employee[0].FullName)
                </a>
            </th>
            <th>
                 <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Subdivision",Model.CurrentSortOrder)">
                @Html.DisplayNameFor(model => model.Employee[0].Subdivision)
                </a>
            </th>
            <th>
                 <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Position",Model.CurrentSortOrder)">
                @Html.DisplayNameFor(model => model.Employee[0].Position)
                </a>
            </th>
            <th>
                 <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("Status",Model.CurrentSortOrder)">
                @Html.DisplayNameFor(model => model.Employee[0].Status)
                </a>
            </th>
            <th>
                 <a asp-page="./Index" asp-route-sortOrder="@Model.GetSortOrder("DaysOff",Model.CurrentSortOrder)">
                @Html.DisplayNameFor(model => model.Employee[0].DaysOff)
                </a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Employee) {
        <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subdivision)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DaysOff)
            </td>
            <td>
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> 

                        @if (User.IsInRole("Admin") || User.IsInRole("HR"))
                        {
                            <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a>
                            <form method="post" asp-page-handler="ChangeStatus" style="display:inline;">
                                <input type="hidden" name="id" value="@item.Id" />
                                <button class="btn btn-outline-dark flex-shrink-0" type="submit">
                                    Change Status
                                </button>
                            </form>
                        }
                    @if (User.IsInRole("Supervisor"))
                    {
                        <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                    }
            </td>
        </tr>
}
    </tbody>
</table>
</div>